import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    name: "Boat Air Dopes",
    image:
      "https://drive.google.com/uc?export=view&id=132cLoMt9OzjVD9T7em1vkrnJ8Co-uHXW",
    price: "1200.00",
    brand: "Boat",
    categoryName: "Ear Phones",
    inStock: 7,
    fastDelivery: true,
    ratings: 4.5,
    reviews: 1993,
  },
  {
    _id: uuid(),
    name: "JBL Earphones",
    image:
      "https://drive.google.com/uc?export=view&id=1bZhEMD46AmPyxMa1kT2nHxQa2wWpZbF_",
    price: "699.00",
    brand: "JBL",
    categoryName: "Ear Phones",
    inStock: 5,
    fastDelivery: true,
    ratings: 4.0,
    reviews: 388,
  },
  {
    _id: uuid(),
    name: "Realme Buds",
    image:
      "https://drive.google.com/uc?export=view&id=1lcPFJAH5T012opERMsxYWDOX4wZJawdE",
    price: "1600.00",
    brand: "Realme",
    categoryName: "Ear Phones",
    inStock: 3,
    fastDelivery: true,
    ratings: 4.6,
    reviews: 399,
  },
  {
    _id: uuid(),
    name: "Sony Ear Phones",
    image:
      "https://drive.google.com/uc?export=view&id=1m66ed0vZPHch2ArwdwE2Esta4DXLdEWN",
    price: "800.00",
    brand: "Sony",
    categoryName: "Ear Phones",
    inStock: 8,
    fastDelivery: true,
    ratings: 4.1,
    reviews: 827,
  },
  {
    _id: uuid(),
    name: "Cosmic Byte GK-16",
    image:
      "https://drive.google.com/uc?export=view&id=1pAvugySg4ppJ3ofNQHLoEOV9Dsv6MLan",
    price: "3100.00",
    brand: "Cosmic Byte",
    categoryName: "Keyboards",
    inStock: 0,
    fastDelivery: true,
    ratings: 4.5,
    reviews: 27,
  },
  {
    _id: uuid(),
    name: "Logitech G213 keyboard",
    image:
      "https://drive.google.com/uc?export=view&id=1z8vkJSFpFWvCX-fGztWFKi9Hu5LXyvwl",
    price: "2500.00",
    brand: "Logitech",
    categoryName: "Keyboards",
    inStock: 6,
    fastDelivery: true,
    ratings: 4.1,
    reviews: 837,
  },
  {
    _id: uuid(),
    name: "HP GK-16",
    image:
      "https://drive.google.com/uc?export=view&id=1hC7YSqUbzrEMYF5141nWApfJA70AAKQb",
    price: "2900.00",
    brand: "HP",
    categoryName: "Keyboards",
    inStock: 4,
    fastDelivery: true,
    ratings: 4.2,
    reviews: 938,
  },
  {
    _id: uuid(),
    name: "Zebronics Transformer",
    image:
      "https://drive.google.com/uc?export=view&id=1BvksK6LkeKhU7qfQ1GM8Y64BZ7KRIhED",
    price: "2600.00",
    brand: "Zebronics",
    categoryName: "Keyboards",
    inStock: 4,
    fastDelivery: true,
    ratings: 4.0,
    reviews: 432,
  },
  {
    _id: uuid(),
    name: "iPhone 13",
    image:
      "https://drive.google.com/uc?export=view&id=1_Fj3AZUQqlLgpkoE2r2I70OR2aWlmj6C",
    price: "80699.00",
    brand: "Apple",
    categoryName: "Mobile Phones",
    inStock: 2,
    fastDelivery: true,
    ratings: 4.8,
    reviews: 1837,
  },
  {
    _id: uuid(),
    name: "Realme c31",
    image:
      "https://drive.google.com/uc?export=view&id=1tvZTBTVTVn6NmVtBG6oZ5l_6QgI3-m5n",
    price: "9499.00",
    brand: "Realme",
    categoryName: "Mobile Phones",
    inStock: 0,
    fastDelivery: true,
    ratings: 3.5,
    reviews: 74,
  },
  {
    _id: uuid(),
    name: "Reno 6 Pro",
    image:
      "https://drive.google.com/uc?export=view&id=181QOCBtLqTsjhN9MY8dklPDksquIlFH3",
    price: "39900.00",
    brand: "Oppo",
    categoryName: "Mobile Phones",
    inStock: 12,
    fastDelivery: true,
    ratings: 4.5,
    reviews: 83,
  },
  {
    _id: uuid(),
    name: "Samsung Galaxy S21",
    image:
      "https://drive.google.com/uc?export=view&id=1tHqjSD87FbFRAPhQPnW7hv-5sQGiIYO6",
    price: "51900.00",
    brand: "Samsung",
    categoryName: "Mobile Phones",
    inStock: 3,
    fastDelivery: true,
    ratings: 4.6,
    reviews: 899,
  },
  {
    _id: uuid(),
    name: "iPad 9th Gen",
    image:
      "https://drive.google.com/uc?export=view&id=1V5eDqKPhXG_5ZRnOaJYTUVJTddz-iU_s",
    price: "60000.00",
    brand: "Apple",
    categoryName: "Tablets",
    inStock: 0,
    fastDelivery: true,
    ratings: 4.6,
    reviews: 1399,
  },
  {
    _id: uuid(),
    name: "Lenovo Yoga",
    image:
      "https://drive.google.com/uc?export=view&id=1s5gVprB7fjl-Ckw3wUIyjXHtGe4oAmuK",
    price: "34000.00",
    brand: "Lenovo",
    categoryName: "Tablets",
    inStock: 3,
    fastDelivery: true,
    ratings: 2.9,
    reviews: 165,
  },
  {
    _id: uuid(),
    name: "Realme Pad 4",
    image:
      "https://drive.google.com/uc?export=view&id=1vW-C4bIRJaAaLbMZsgy42SIgPlJ-KXk6",
    price: "19000.00",
    brand: "Realme",
    categoryName: "Tablets",
    inStock: 8,
    fastDelivery: true,
    ratings: 3.5,
    reviews: 65,
  },
  {
    _id: uuid(),
    name: "Samsung Tab S8",
    image:
      "https://drive.google.com/uc?export=view&id=1gqIVVX3nS9nsO2vBTk724bI7Jb_iQjSn",
    price: "59000.00",
    brand: "Samsung",
    categoryName: "Tablets",
    inStock: 4,
    fastDelivery: false,
    ratings: 4.5,
    reviews: 1256,
  },
];
